# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7da050e05b4467ee495befd5d09cafb5e9f0349e929ca64c349b3c48037bb5741c454e4b00c6150f936e75b783c50f2604339087c96c66fdc38cf58d2e048647

test:
  secret_key_base: d41ba9b53a7a15b12d00a03777b2708781a3e5096f9e9ffebf974e9362099355325c707d82700bc20ad826af09ebc84e0d8f6d65866f277a195ca1fb71f26749

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
